export const DRAFT_STEPS = [
  { side: 'Blue', type: 'BAN', label: 'Xanh Cấm 1' },
  { side: 'Red', type: 'BAN', label: 'Đỏ Cấm 1' },
  { side: 'Blue', type: 'BAN', label: 'Xanh Cấm 2' },
  { side: 'Red', type: 'BAN', label: 'Đỏ Cấm 2' },
  { side: 'Blue', type: 'PICK', label: 'Xanh Chọn 1' },
  { side: 'Red', type: 'PICK', label: 'Đỏ Chọn 1' },
  { side: 'Red', type: 'PICK', label: 'Đỏ Chọn 2' },
  { side: 'Blue', type: 'PICK', label: 'Xanh Chọn 2' },
  { side: 'Blue', type: 'PICK', label: 'Xanh Chọn 3' },
  { side: 'Red', type: 'PICK', label: 'Đỏ Chọn 3' },
  { side: 'Red', type: 'BAN', label: 'Đỏ Cấm 3' },
  { side: 'Blue', type: 'BAN', label: 'Xanh Cấm 3' },
  { side: 'Red', type: 'BAN', label: 'Đỏ Cấm 4' },
  { side: 'Blue', type: 'BAN', label: 'Xanh Cấm 4' },
  { side: 'Red', type: 'PICK', label: 'Đỏ Chọn 4' },
  { side: 'Blue', type: 'PICK', label: 'Xanh Chọn 4' },
  { side: 'Blue', type: 'PICK', label: 'Xanh Chọn 5' },
  { side: 'Red', type: 'PICK', label: 'Đỏ Chọn 5' },
];